function gene_order = MAPK_gene_order()


gene_order = {'ERK', 'p38', 'JNK', 'p53', 'p21', 'TGFBR', 'EGFR', 'FGFR3',...
    'ATM', 'TAOK', 'MAX', 'GRB2', 'FRS2', 'PI3K', 'AP1', 'PPP2CA',...
    'MEK1_2', 'DUSP1', 'MYC', 'AKT', 'PLCG', 'PKC', 'GADD45', 'ELK1',...
    'FOS', 'ATF2', 'JUN', 'MSK', 'CREB', 'RSK', 'SMAD','MTK1', 'SPRY',...
    'RAF', 'GAB1', 'PDK1', 'p70', 'p14', 'FOXO3', 'RAS', 'SOS', 'MDM2',...
    'BCL2', 'TAK1', 'MAP3K1_3', 'PTEN', ... %'HIF1',
    'Proliferation','Apoptosis',...
    'Growth_Arrest'};